# Generated by Django 4.1 on 2022-09-17 22:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pergunta', models.CharField(max_length=200)),
                ('pergunta', models.TextField(max_length=2500)),
                ('intro_pergunta', models.TextField(max_length=150)),
                ('comentario', models.TextField(blank=True, max_length=2500)),
                ('email_comentario', models.CharField(blank=True, max_length=200)),
                ('disciplina', models.CharField(max_length=150)),
                ('faculdade', models.CharField(max_length=150)),
                ('date_pergunta', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('publicada', models.BooleanField(default=False)),
                ('revisao_solicitada', models.BooleanField(default=False)),
                ('revisao_qtd', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_revisor', models.CharField(blank=True, max_length=200)),
                ('revisao', models.TextField(blank=True, max_length=2000)),
                ('revisada', models.BooleanField(default=False)),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='LikeBtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
