# Generated by Django 4.1 on 2022-08-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='intro_pergunta',
            field=models.TextField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
