# Generated by Django 3.2.3 on 2022-08-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_pergunta_intro_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='assessor_email',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
