# Generated by Django 4.1 on 2022-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_remove_pergunta_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nick_comentario',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pergunta',
            name='nick_pergunta',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
