# Generated by Django 4.1 on 2022-09-19 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0003_comentario_nick_comentario_pergunta_nick_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='date_comentario',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
