# Generated by Django 4.1 on 2022-08-22 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0004_alter_pergunta_assessor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='revisada',
            new_name='revisao',
        ),
    ]
