# Generated by Django 4.1 on 2022-08-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0005_rename_revisada_pergunta_revisao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='pessoa',
            new_name='user',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='revisao_qtd',
            field=models.IntegerField(default=0),
        ),
    ]
