# Generated by Django 4.1 on 2022-08-23 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0006_rename_pessoa_pergunta_user_pergunta_revisao_qtd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='revisao',
            new_name='revisao_solicitada',
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisor_email', models.CharField(blank=True, max_length=150)),
                ('comentario_revisao', models.TextField(blank=True, max_length=2000)),
                ('revisada', models.BooleanField(default=False)),
                ('id_pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perguntas.pergunta')),
            ],
        ),
    ]
