# Generated by Django 4.1 on 2022-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0007_rename_comentario_revisao_revisao_revisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.CharField(default='ij93HsaxpaXCk4SgwgpnVk', editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
