# Generated by Django 4.1 on 2022-09-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0013_alter_pergunta_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='id_url',
            field=models.CharField(default='asdfasdf', max_length=22),
            preserve_default=False,
        ),
    ]
