# Generated by Django 4.1 on 2022-10-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0014_pergunta_id_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='intro_pergunta',
            field=models.TextField(max_length=153),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(max_length=6000),
        ),
    ]
