# Generated by Django 4.1 on 2022-10-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0016_alter_pergunta_intro_pergunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='intro_pergunta',
            field=models.TextField(max_length=403),
        ),
    ]
