# Generated by Django 4.1 on 2022-10-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0017_alter_pergunta_intro_pergunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='pageviews',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
