# Generated by Django 4.1 on 2022-11-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0018_pergunta_pageviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='listada',
            field=models.BooleanField(default=True),
        ),
    ]
