# Generated by Django 4.1 on 2022-11-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0019_pergunta_listada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta',
            field=models.TextField(max_length=25000),
        ),
    ]
