# Generated by Django 4.1 on 2022-08-15 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensalidade', models.BooleanField(default=False)),
                ('CPF', models.CharField(max_length=200, unique=True)),
                ('instagram', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=25)),
                ('linkedIn', models.CharField(max_length=80)),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
