# Generated by Django 4.1 on 2022-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
