# Generated by Django 4.1 on 2022-09-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='CPF',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinante',
            name='descricao',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='assinante',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinante',
            name='facebook',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assinante',
            name='foto',
            field=models.ImageField(blank=True, default='/media/usuarios/no-image.png', upload_to='media/usuarios/'),
        ),
        migrations.AddField(
            model_name='assinante',
            name='homepage',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assinante',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assinante',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assinante',
            name='mensalidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assinante',
            name='nome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinante',
            name='plano',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assinante',
            name='resumo',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='assinante',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='assinante',
            name='sobrenome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='assinante',
            name='whatsapp_ddd',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='assinante',
            name='whatsapp_ddi',
            field=models.CharField(default='+55', max_length=3),
        ),
        migrations.AddField(
            model_name='assinante',
            name='youtube',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
