# Generated by Django 4.1 on 2022-09-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='plano',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='foto',
            field=models.ImageField(blank=True, default='/media/usuarios/no-image.png', upload_to='papiron/static/media/usuarios/'),
        ),
    ]
