# Generated by Django 4.1 on 2022-09-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_assinante_cpf_assinante_descricao_assinante_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='nick_assinante',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
