# Generated by Django 4.1 on 2022-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_assinante_instagram_alter_assinante_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
