# Generated by Django 4.1 on 2022-09-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_assinante_nick_assinante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='nick_assinante',
        ),
    ]
