# Generated by Django 4.1 on 2022-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_assinante_nick_assinante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='nick_assinante',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
