# Generated by Django 3.2.3 on 2022-08-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20220817_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
