# Generated by Django 4.1 on 2022-09-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_assinante_nick_assinante'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='id_perfil',
            field=models.CharField(default='a1s2j', max_length=5),
            preserve_default=False,
        ),
    ]
