# Generated by Django 3.2.3 on 2022-08-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_assinante_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
