# Generated by Django 4.1 on 2022-09-23 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_assinante_id_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinante',
            old_name='nick_assinante',
            new_name='nick',
        ),
    ]
