# Generated by Django 4.1 on 2022-10-07 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_rename_nick_assinante_assinante_nick'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculdade', models.CharField(blank=True, max_length=250)),
                ('disciplina', models.CharField(blank=True, max_length=250)),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.assinante')),
            ],
        ),
    ]
