# Generated by Django 3.2.3 on 2022-08-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_assinante_foto_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='foto_receita',
            field=models.ImageField(blank=True, default='fotos/no-image.jpg', upload_to='fotos/'),
        ),
    ]
