# Generated by Django 3.2.3 on 2022-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_assinante_foto_receita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='foto_receita',
        ),
        migrations.AddField(
            model_name='assinante',
            name='foto',
            field=models.ImageField(blank=True, default='static/img/usuarios-img/no-image.png', upload_to='static/img/usuarios-img/'),
        ),
        migrations.AddField(
            model_name='assinante',
            name='nome',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assinante',
            name='sobrenome',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
