# Generated by Django 3.2.3 on 2022-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20220821_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='descricao',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
