# Generated by Django 4.1 on 2022-10-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_stat_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='exclusivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='peso',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='especialidade',
            name='rodada',
            field=models.BooleanField(default=False),
        ),
    ]
