# Generated by Django 4.1 on 2022-08-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_assinante_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_register', models.CharField(max_length=200)),
                ('code_sent', models.IntegerField()),
                ('data_code', models.DateField()),
            ],
        ),
    ]
