# Generated by Django 4.1 on 2022-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_registro_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_email',
            name='approve_code',
            field=models.BooleanField(default=False),
        ),
    ]
