# Generated by Django 4.1 on 2022-09-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_registro_email_approve_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinante',
            name='foto',
            field=models.ImageField(blank=True, default='media/usuarios/no-image.png', upload_to='media/usuarios/'),
        ),
    ]
