# Generated by Django 4.1 on 2022-09-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_assinante_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='assinante',
            name='foto',
            field=models.ImageField(blank=True, default='papiron/static/media/usuarios/no-image.png', upload_to='papiron/static/media/usuarios/'),
        ),
    ]
