# Generated by Django 4.1 on 2022-09-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_assinante_score_alter_assinante_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='whatsapp_ddd',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
