# Generated by Django 3.2.3 on 2022-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20220817_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='descricao',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
