# Generated by Django 3.2.3 on 2022-08-17 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20220817_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assinante',
            name='descricao',
        ),
    ]
