# Generated by Django 3.2.3 on 2022-08-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_assinante_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinante',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
